# Download Script for Salesforce Flow Images
# NOTE: URLs below are estimated and may not be accurate.
# Visit the articles manually to get correct image URLs, then update this script.

# Create images directory
mkdir -p /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images

# Download images from "Your Complete Guide to Available Types of Flow in Salesforce"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/flow_types_overview.png "https://www.salesforceben.com/wp-content/uploads/2022/01/flow-types-overview.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/screen_flow_example.png "https://www.salesforceben.com/wp-content/uploads/2022/01/screen-flow-example.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/record_triggered_flow.png "https://www.salesforceben.com/wp-content/uploads/2022/01/record-triggered-flow.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/autolaunched_flow.png "https://www.salesforceben.com/wp-content/uploads/2022/01/autolaunched-flow.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/schedule_triggered_flow.png "https://www.salesforceben.com/wp-content/uploads/2022/01/schedule-triggered-flow.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/platform_event_flow.png "https://www.salesforceben.com/wp-content/uploads/2022/01/platform-event-flow.png"

# Download images from "Salesforce Flow Best Practices"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/flow_canvas_organization.png "https://www.salesforceben.com/wp-content/uploads/2022/01/flow-canvas-organization.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/error_handling_pattern.png "https://www.salesforceben.com/wp-content/uploads/2022/01/error-handling-pattern.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/bulkification_example.png "https://www.salesforceben.com/wp-content/uploads/2022/01/bulkification-example.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/decision_best_practice.png "https://www.salesforceben.com/wp-content/uploads/2022/01/decision-best-practice.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/variable_naming.png "https://www.salesforceben.com/wp-content/uploads/2022/01/variable-naming.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/flow_testing_strategy.png "https://www.salesforceben.com/wp-content/uploads/2022/01/flow-testing-strategy.png"

# Download images from "Salesforce Platform Events"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/platform_event_definition.png "https://www.salesforceben.com/wp-content/uploads/2023/01/platform-event-definition.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/event_publishing_process.png "https://www.salesforceben.com/wp-content/uploads/2023/01/event-publishing-process.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/event_driven_flow.png "https://www.salesforceben.com/wp-content/uploads/2023/01/event-driven-flow.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/cometd_subscription.png "https://www.salesforceben.com/wp-content/uploads/2023/01/cometd-subscription.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/external_integration.png "https://www.salesforceben.com/wp-content/uploads/2023/01/external-integration.png"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/replay_id_management.png "https://www.salesforceben.com/wp-content/uploads/2023/01/replay-id-management.png"

# Download images from "Salesforce Flow Glossary" (Flow Builder features)
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az1.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az1.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az2.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az2.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az3.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az3.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az4.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az4.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az5.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az5.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az6.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az6.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az7.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az7.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az8.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az8.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az9.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az9.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az10.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az10.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az11.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az11.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az12.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az12.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az13.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az13.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az14.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az14.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az15.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az15.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az16.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az16.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az17.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az17.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az18.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az18.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az19.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az19-1.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az20.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az20.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az21.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az21.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az22.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az22.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az23.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az23.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az24.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az24.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az25.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az25.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az26.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az26.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az27.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az27.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az28.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az28.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az29.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az29.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az30.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az30.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az31.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az31.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az32.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az32.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az33.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az33.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az34.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az34.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az35.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az35.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az36.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az36-1024x297.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az37.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az37.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az38.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az38.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az39.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az39.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az40.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az40.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az41.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az41.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az42.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az42.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az43.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az43.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az44.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az44.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az45.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az45.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az46.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az46.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az47.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az47.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az48.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az48.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az49.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az49.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az50.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az50.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az51.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az51.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az52.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az52.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az53.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az53.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az54.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az54.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az55.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az55.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az56.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az56.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az57.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az57.webp"
curl -L -o /home/erpnext/frappe-bench/apps/flexirule/salesforce_flow_to_flexirule/reference/images/az58.webp "https://www.salesforceben.com/wp-content/uploads/2023/03/az58.webp"