title = "FlexiRule Documentation"
baseurl = "https://sendipad.github.io/flexirule/docs/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"

[caches]
  [caches.getremote]
    dir = ":cacheDir/:project"
    maxAge = -1

[taxonomies]
  contributor = "contributors"
  category = "categories"
  tag = "tags"

[permalinks]
  docs = "/docs/:sections[1:]/:slug/"
